### ISSUE TITLE
How to use cachix binary system-wide

### ISSUE THREAD

**Issue by lem0n4de** [Infinisil/all-hies#11]
Hi,
I wanted to use cachix binaries but after `cachix use all-hies` I still can not access hie binaries. What should I do to get system-wide binaries? My primary objective is to use it with Visual Studio Code.

**Comment by infinisil** [comment]
- What OS are you on?
- What's the Nix expression you use for `all-hies`? And how are you calling it?
- How do you know that you can't access the binaries? Can you show the logs of it?
- What does `cachix use all-hies` output?

**Comment by lem0n4de** [comment]
1. I am on NixOS. This is the output of  `nix-shell -p nix-info --run "nix-info -m"`:
   - system: `"x86_64-linux"`
   - host os: `Linux 4.19.46, NixOS, 19.03.172764.50d5d73e22b (Koi)`
   - multi-user?: `yes`
   - sandbox: `yes`
   - version: `nix-env (Nix) 2.2.2`
   - channels(lem0n): `"home-manager"`
   - channels(root): `"nixos-19.03.172764.50d5d73e22b, home-manager"`
   - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

2. I tried running `hie-wrapper`. Output was `zsh: command not found: hie-wrapper`
3. I don't know actually. They are just not on $PATH.
4. Output is this. I did import cachix in /etc/nixos/configuration.nix
```Cachix configuration written to /etc/nixos/cachix.nix.
Binary cache all-hies configuration written to /etc/nixos/cachix/all-hies.nix.

To start using cachix add the following to your /etc/nixos/configuration.nix:

    imports = [ ./cachix.nix ];

Then run:

    $ nixos-rebuild switch```

**Comment by infinisil** [comment]
Did you follow the [NixOS installation section](https://github.com/infinisil/all-hies#nixos-installation)?

**Comment by lem0n4de** [comment]
Yes, I had followed, builded and used that way successfully. But I want to use cached binaries now as building takes too long.

**Comment by infinisil** [comment]
What does `cat /etc/nix/nix.conf` output?

**Comment by lem0n4de** [comment]
This: 
```
# WARNING: this file is generated from the nix.* options in
# your NixOS configuration, typically
# /etc/nixos/configuration.nix.  Do not edit it!
build-users-group = nixbld
max-jobs = 4
cores = 0
sandbox = true
extra-sandbox-paths =  
substituters = https://all-hies.cachix.org https://cache.nixos.org/
trusted-substituters = 
trusted-public-keys = all-hies.cachix.org-1:JjrzAOEUsD9ZMt8fdFbzo3jNAyEWlPAwdVuHw4RD43k= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
auto-optimise-store = false
require-sigs = true

trusted-users = root
allowed-users = *
builders =
```

**Comment by infinisil** [comment]
That looks all good. Now try installing HIE (as per the instructions in the readme, by adding it to your configuration.nix), but use `nixos-rebuild switch -j0 -k` and show the result of that.

**Comment by lem0n4de** [comment]
I thought that the `(all-hies.selectors ...)` line in systemPackages builds the package so I deleted it and expected to have the package. I appearently did not understand how NixOS caches worked. Sorry to bother you. It is now solved.
