### ISSUE TITLE
Error in vscode: can't load .so/.DLL for (...) libcurl.so.4, no such file or directory

### ISSUE THREAD

**Issue by SandiCat** [Infinisil/all-hies#17]
Here's the full error from VSCode. It pops up when I open up a haskell project, with the haskell-language-server extension installed.

```<command line>: can't load .so/.DLL for: /home/sandi/.stack/snapshots/x86_64-linux-tinfo6/lts-13.30/8.6.5/lib/x86_64-linux-ghc-8.6.5/libHScurl-1.3.8-4DmDUg4lWOTAEuPJAIVP0I-ghc8.6.5.so (libcurl.so.4: cannot open shared object file: No such file or directory)\n```

I installed the binaries (after setting up cachix as described) with the following commands:
```
$ nix-env -iA selection --arg selector 'p: { inherit (p) ghc864 ghc863 ghc843; }' -f https://github.com/infinisil/all-hies/tarball/master
$ nix-env -iA selection --arg selector 'p: { inherit (p) ghc865; }' -f https://github.com/infinisil/all-hies/tarball/master
```

I'm running Manjaro Linux, an Arch Linux derivative. Other info:
```
$ uname -a
Linux pc 4.19.59-1-MANJARO #1 SMP PREEMPT Mon Jul 15 18:23:58 UTC 2019 x86_64 GNU/Linux
$ stack --version
Version 1.9.3.1, Git revision 43ff632b030f50898bff793c9e6c634637ba6001 (6217 commits) x86_64
$ nix --version
nix (Nix) 2.2.2
```

Sadly, I don't know how to use nix. This seems to be some kind of dependency conflict? From what I understand that isn't supposed to happen with nix, but maybe it's because the binaries have some runtime dependencies? No idea, to be honest.

**Comment by infinisil** [comment]
Doesn't look Nix-related. I'd try doing a `stack clean`, `stack build` and restart vs code, or clean the `.stack` directory if that doesn't do it.

**Comment by SandiCat** [comment]
I did both, it did not resolve the issue. I also updated my system and restarted my computer.

There's an additional error now, appearing after the first one:
```
Got error while processing diagnostics: GHC panic! (the 'impossible' happened)
  ghc-mod version 5.9.0.0
  GHC library version 8.6.5 for x86_64-unknown-linux:
       Dynamic linker not initialised

Please report this as a bug: https://github.com/kazu-yamamoto/ghc-mod/issues
```

I'm not sure if this is relevant, but there does appear to be a libcurl.so.4 on my system:
```
 $ ls /usr/lib | grep curl
libcurl-gnutls.so.3
libcurl-gnutls.so.4
libcurl-gnutls.so.4.0.0
libcurl-gnutls.so.4.1.0
libcurl-gnutls.so.4.2.0
libcurl-gnutls.so.4.3.0
libcurl-gnutls.so.4.4.0
libcurl-gnutls.so.4.5.0
libcurl.so
libcurl.so.4
libcurl.so.4.5.0
```

**Comment by SandiCat** [comment]
**Solved!** This fixed it:
```
$ sudo stack upgrade
```

I was suddenly getting lots of `thread blocked indefinitely in an STM transaction` errors from stack, googling yielded this comment that suggested the fix: https://github.com/haskell/haskell-ide-engine/issues/1328#issuecomment-513575755

**Comment by infinisil** [comment]
Glad you got it figured out :)

**Comment by SandiCat** [comment]
False alarm. It works on `stack new` projects, but not in the project I originally got the error on. 

After a few hours, I managed to get very close to a minimal reproduction. Steps to reproduce:

1. Clone https://github.com/SandiDusic/hie-vscode-error
2. `stack build`
3. Open vscode with the hie extension
4. Wait a bit
5. See the error from the original post pop up

The project has a single source file that is basically just `LANGUAGE` pragmas. It also has a few dependencies. Remove either, and there's no error. I also get the exact same error with the `yesod/sqlite3` stack template.

My suspicion is on the packages `attoparsec`, `aeson` and `scalpel`, because the error is about the `curl` package. If I remove `scalpel` which depends on it, the error disappears. But then an error about the package `scientific` appears. If I remove `attoparsec` and `aeson` which depend on it, it disappears.

Am I barking up the wrong tree? Should this be posted on HIE's or the extension's or ghc-mod's github issues?

**Comment by infinisil** [comment]
I see, what's the output of running this?
```
$ ldd /home/sandi/.stack/snapshots/x86_64-linux-tinfo6/lts-13.30/8.6.5/lib/x86_64-linux-ghc-8.6.5/libHScurl-1.3.8-4DmDUg4lWOTAEuPJAIVP0I-ghc8.6.5.so
```

(Or whatever ghc8.6.5.so file you get in your error)

**Comment by SandiCat** [comment]
Here it is:
```
        linux-vdso.so.1 (0x00007ffcd86fd000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007f268b9bd000)
        libcurl.so.4 => /usr/lib/libcurl.so.4 (0x00007f268b931000)
        libHScontainers-0.6.0.1-ghc8.6.5.so => /home/sandi/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.5/lib/ghc-8.6.5/containers-0.6.0.1/libHScontainers-0.6.0.1-ghc8.6.5.so (0x00007f268b5cb000)
        libHSbytestring-0.10.8.2-ghc8.6.5.so => /home/sandi/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.5/lib/ghc-8.6.5/bytestring-0.10.8.2/libHSbytestring-0.10.8.2-ghc8.6.5.so (0x00007f268b4df000)
        libHSdeepseq-1.4.4.0-ghc8.6.5.so => /home/sandi/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.5/lib/ghc-8.6.5/deepseq-1.4.4.0/libHSdeepseq-1.4.4.0-ghc8.6.5.so (0x00007f268b4c5000)
        libHSarray-0.5.3.0-ghc8.6.5.so => /home/sandi/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.5/lib/ghc-8.6.5/array-0.5.3.0/libHSarray-0.5.3.0-ghc8.6.5.so (0x00007f268b443000)
        libHSbase-4.12.0.0-ghc8.6.5.so => /home/sandi/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.5/lib/ghc-8.6.5/base-4.12.0.0/libHSbase-4.12.0.0-ghc8.6.5.so (0x00007f268aabe000)
        libHSinteger-gmp-1.0.2.0-ghc8.6.5.so => /home/sandi/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.5/lib/ghc-8.6.5/integer-gmp-1.0.2.0/libHSinteger-gmp-1.0.2.0-ghc8.6.5.so (0x00007f268aa7e000)
        libHSghc-prim-0.5.3-ghc8.6.5.so => /home/sandi/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.5/lib/ghc-8.6.5/ghc-prim-0.5.3/libHSghc-prim-0.5.3-ghc8.6.5.so (0x00007f268a5ec000)
        libgmp.so.10 => /usr/lib/libgmp.so.10 (0x00007f268a558000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f268a395000)
        /usr/lib64/ld-linux-x86-64.so.2 (0x00007f268bc24000)
        libnghttp2.so.14 => /usr/lib/libnghttp2.so.14 (0x00007f268a36d000)
        libidn2.so.0 => /usr/lib/libidn2.so.0 (0x00007f268a34e000)
        libssh2.so.1 => /usr/lib/libssh2.so.1 (0x00007f268a31d000)
        libpsl.so.5 => /usr/lib/libpsl.so.5 (0x00007f268a308000)
        libssl.so.1.1 => /usr/lib/libssl.so.1.1 (0x00007f268a278000)
        libcrypto.so.1.1 => /usr/lib/libcrypto.so.1.1 (0x00007f2689fa4000)
        libgssapi_krb5.so.2 => /usr/lib/libgssapi_krb5.so.2 (0x00007f2689f54000)
        libkrb5.so.3 => /usr/lib/libkrb5.so.3 (0x00007f2689e66000)
        libk5crypto.so.3 => /usr/lib/libk5crypto.so.3 (0x00007f2689e31000)
        libcom_err.so.2 => /usr/lib/libcom_err.so.2 (0x00007f2689e29000)
        libz.so.1 => /usr/lib/libz.so.1 (0x00007f2689c12000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f2689bf1000)
        libunistring.so.2 => /usr/lib/libunistring.so.2 (0x00007f2689871000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f268986c000)
        libkrb5support.so.0 => /usr/lib/libkrb5support.so.0 (0x00007f268985a000)
        libkeyutils.so.1 => /usr/lib/libkeyutils.so.1 (0x00007f2689853000)
        libresolv.so.2 => /usr/lib/libresolv.so.2 (0x00007f268983a000)
```

The error about `scientific` is also interesting, it mentions glibc and nix:
```<command line>: can't load .so/.DLL for: /home/sandi/.stack/snapshots/x86_64-linux-tinfo6/783196fd86b5d5c4c641e9cb344bfaebc3e80555f2ac50cdb838948ebb2f067e/8.6.5/lib/x86_64-linux-ghc-8.6.5/libHSscientific-0.3.6.2-BboXwnuKby4BtCVtfss4TP-ghc8.6.5.so (/nix/store/c745s6cnnxy6c98bvhi0qsijrh3ikag1-glibc-2.27/lib/libm.so.6: version `GLIBC_2.29' not found (required by /home/sandi/.stack/snapshots/x86_64-linux-tinfo6/783196fd86b5d5c4c641e9cb344bfaebc3e80555f2ac50cdb838948ebb2f067e/8.6.5/lib/x86_64-linux-ghc-8.6.5/libHSscientific-0.3.6.2-BboXwnuKby4BtCVtfss4TP-ghc8.6.5.so))\n```

Out of curiosity, were you able to reproduce it?

**Comment by infinisil** [comment]
Nope, I wasn't able to reproduce it. It would be interesting to know whether the non-Nix installation method works for you. I'm pretty much clueless as to what could be the problem here.

**Comment by SandiCat** [comment]
Welp, I built it from source and it works. I'm not sure if I should close the issue since it wasn't really resolved.

**Comment by infinisil** [comment]
It still is an issue, all-hies is supposed towork on other distros as well. Maybe it'll take some time to resolve though

**Comment by Infinisil** [comment]
It still is an issue, all-hies is supposed towork on other distros as well. Maybe it'll take some time to resolve though

**Comment by drewboardman** [comment]
I found a way to reliably reproduce this issue.

Steps

1. [Clone this repo](https://github.com/drewboardman/fp-course/tree/nix_error) and checkout the `nix_error` branch.

2. Enter a `nix-shell` and let it install stack, hie.

3. Build the project with `stack build`.

4. run `hie-wrapper --debug`. This produces the following errors:

```
 Ghc error on cradle initialisation: "panic! (the 'impossible' happened)\n  (GHC version 8.6.5 for x86_64-unknown-linux):\n\tDynamic linker not initialised\n\nPlease report this as a GHC bug:  http://www.haskell.org/ghc/reportabug\n"
```

5. run `hie-wrapper --debug src/Traversable.hs`. You will get the following error:

```
"can't load .so/.DLL for: libgmp.so (libgmp.so: cannot open shared object file: No such file or directory)"
```

**Comment by infinisil** [comment]
With #64 merged, the project has been changed considerably. If this is still an issue and people are interested to try it again, now is the time :). Maybe check out the new project templates that demonstrate how to get a working environment: https://github.com/Infinisil/all-hies/tree/master/templates

**Comment by infinisil** [comment]
Closing all issues for deprecation and archival, refer to https://github.com/haskell/haskell-language-server instead
