### ISSUE TITLE
Support building any HIE version

### ISSUE THREAD

**Issue by infinisil** [Infinisil/all-hies#2]
The code supports this already pretty much, just needs some good ideas how to export it, potentially:
- Expose both stable and master version, master gets updated once every week or so
- Add an argument to `update.hs` to select the version you want to generate, either a tag or a revision

**Comment by infinisil** [comment]
Especially important now that stable HIE doesn't have a version for GHC 8.6.5, but nixpkgs master already has that GHC version.

**Comment by infinisil** [comment]
Since 8a3a0c0202c114ec81d5ed9d153e560db5beb7a3, the update script supports taking an arbitrary HIE revision as an argument.

**Comment by srghma** [comment]
is there a version for 8.6.5 already?

**Comment by infinisil** [comment]
@srghma I am working on it, see #8 for updates, thanks for the ping :)
