### ISSUE TITLE
How to install by using the ~/.nixpkgs/config.nix

### ISSUE THREAD

**Issue by freeman42x** [Infinisil/all-hies#20]
Could you add a section to the documentation that explains how to do that please?

**Comment by freeman42x** [comment]
I got it working using the following:

```nix
let
  all-hies = import (fetchTarball "https://github.com/infinisil/all-hies/tarball/master") {};
  config = {
    allowUnfree = true;
    
    packageOverrides = pkgs: with pkgs; 
      let jdk = openjdk11; in rec {
      unstable = import <nixpkgs> { inherit config; };
      
      all = pkgs.buildEnv {
        name = "all";

        paths = [
          htop
          nox
          nix-info
          nix-index
          google-chrome
          nodejs-11_x
          binutils.bintools
          haskell.compiler.ghc864
          haskellPackages.cabal-install
          unstable.haskellPackages.stack
          unstable.haskellPackages.cabal2nix
          haskellPackages.hoogle
          haskellPackages.ghcid
          haskellPackages.phoityne-vscode
          haskellPackages.haskell-dap
          (all-hies.selection { selector = p: { inherit (p) ghc864; }; })
        ];
      };
    };
  };
in config
```

**Comment by freeman42x** [comment]
Created a PR for documentation changes: https://github.com/Infinisil/all-hies/pull/21/files

**Comment by infinisil** [comment]
(see discussion in https://github.com/Infinisil/all-hies/pull/21)

**Comment by waiting-for-dev** [comment]
Hey @razvan-flavius-panda .

Sorry for the direct mention, but I'd like to ask for your help as I'm also trying to make hie to work in a declarative way (in my case, in a NixOS installation). It seems I got some pieces well but others are missing. I wrote all the details on [NixOS discussion forum](https://discourse.nixos.org/t/configuration-needed-for-haskell-ide-environment/4240) and on [Haskell Cafe mailing list](https://mail.haskell.org/pipermail/haskell-cafe/2019-October/131569.html). No luck for now...

Thanks for any advice you can give me...

**Comment by freeman42x** [comment]
@waiting-for-dev Since HIE is installed and working but only for some use-cases I have no idea.
