### ISSUE TITLE
Can't figure out how to use with cabal 3.0 in a Nix project

### ISSUE THREAD

**Issue by masaeedu** [Infinisil/all-hies#22]
Hello there. I'm kind of stuck trying to figure out how to get hie to play nice with cabal 3. Previously I was using cabal 2 and HIE would break every time I used any of the `new-xyz` commands (apparently the creation of the `dist-newstyle` folder is what confused `cabal-helper-wrapper`). The workaround I settled into was to just use the old deprecated commands to avoid breaking HIE.

In cabal 3 the default commands simply work with `dist-newstyle` now, so `cabal-helper-wrapper` seems to get confused and starts doing strange things like trying to install a private copy of Cabal (even though I already have cabal v3 on my PATH).

I have a simple nix-based project in the git repo [here](https://github.com/masaeedu/tmpfoo). Entering a nix shell or using direnv should reproduce the exact binaries/libraries I have available on the PATH (including `cabal`).

When I start up VS Code under the nix shell, I get:

```
2019-08-31 01:15:03.919667854 [ThreadId 4] - run entered for hie-wrapper(hie-wrapper) Version 0.12.0.0 x86_64 ghc-8.6.5
2019-08-31 01:15:03.920245202 [ThreadId 4] - Current directory:/tmp/tmpfoo
2019-08-31 01:15:03.920549257 [ThreadId 4] - Operating system:linux
2019-08-31 01:15:04.121253504 [ThreadId 4] - Cradle directory:/tmp/tmpfoo
2019-08-31 01:15:04.122881557 [ThreadId 4] - Using plain GHC version
2019-08-31 01:15:04.161018208 [ThreadId 4] - Project GHC version:8.6.5
2019-08-31 01:15:04.161276986 [ThreadId 4] - hie exe candidates :["hie-8.6.5","hie-8.6","hie"]
2019-08-31 01:15:04.162806609 [ThreadId 4] - found hie exe at:/nix/store/xvs0j26jwx1i4p735cjxpjn0z6pq463p-ghc-8.6.5-with-packages/bin/hie-8.6.5
2019-08-31 01:15:04.163114037 [ThreadId 4] - args:[]
2019-08-31 01:15:04.163320861 [ThreadId 4] - launching ....



2019-08-31 01:15:04.505676894 [ThreadId 4] - Using plain GHC version
2019-08-31 01:15:04.536651941 [ThreadId 4] - Run entered for HIE(hie-8.6.5) Version 0.12.0.0 x86_64 ghc-8.6.5
2019-08-31 01:15:04.537148891 [ThreadId 4] - Current directory:/tmp/tmpfoo
2019-08-31 01:15:04.55389384 [ThreadId 10] - Using plain GHC version
Using hie version: Version 0.12.0.0 x86_64 ghc-8.6.5
cabal-helper-wrapper: Installing a private copy of Cabal because we couldn't
find the right version in your global/user package-db, this might take a
while but will only happen once per Cabal version you're using.

If anything goes horribly wrong just delete this directory and try again:
    /home/ankh/.cache/cabal-helper

If you want to avoid this automatic installation altogether install
version 3.0.0.0 of Cabal manually (into your user or global package-db):
    $ cabal install Cabal --constraint "Cabal == 3.0.0.0"

Installing Cabal 3.0.0.0 ...
Warning: The package list for 'hackage.haskell.org' does not exist. Run 'cabal
update' to download it.
cabal: There is no package named 'Cabal'.
You may need to run 'cabal update' to get the latest list of available
packages.

cabal-helper-wrapper: Installing Cabal version 3.0.0.0 failed.

You have the following choices to fix this:

- The easiest way to try and fix this is just reconfigure the project and try
  again:
        $ cabal clean && cabal configure

- If that fails you can try to install the version of Cabal mentioned above
  into your global/user package-db somehow, you'll probably have to fix
  something otherwise it wouldn't have failed above:
        $ cabal install Cabal --constraint 'Cabal == 3.0.0.0'

- If you're using `Build-Type: Simple`:
  - You can see if you can reinstall your cabal-install executable while
    having it linked to a version of Cabal that's available in you
    package-dbs or can be built automatically:
        $ ghc-pkg list | grep Cabal  # find an available Cabal version
            Cabal-W.X.Y.Z
        $ cabal install cabal-install --constraint 'Cabal == W.X.*'
    Afterwards you'll have to reconfigure your project:
        $ cabal clean && cabal configure

- If you're using `Build-Type: Custom`:
  - Have cabal-install rebuild your Setup.hs executable with a version of the
    Cabal library that you have available in your global/user package-db:
        $ cabal clean && cabal configure
    You might also have to install some version of the Cabal to do this:
        $ cabal install Cabal
```

Any help figuring out how to make this work would be appreciated.

**Comment by masaeedu** [comment]
There's also another slightly confusing issue where you actually have to start by running a `cabal build` once, otherwise the HIE server immediately chokes trying to look for something in the `dist-newstyle` folder (which doesn't yet exist). So to see the error above, please run `cabal build`, then start up the editor.

**Comment by infinisil** [comment]
Turns out this is a HIE problem, I can't fix this with all-hies, see above issue for the development of this. For now the only solution is to not use cabal-install 3.0.0.0 in your project or to try to get an older cabal-install to build with the newer nixpkgs versions, see https://github.com/NixOS/nixpkgs/issues/67761#issuecomment-526673566 too.

**Comment by masaeedu** [comment]
@Infinisil Thanks, that makes sense. I switched back to cabal 2, but I noticed from the debug output that it's still trying to use cabal to install cabal for some reason (see debug output here: https://gist.github.com/masaeedu/5674b9dd6ca95b3b11c23fe17ef7bf8f). This time it is successful, but is this behavior expected?

**Comment by infinisil** [comment]
Yeah that's normal
