### ISSUE TITLE
How to install with nixpkgs channels' ghc version automatically

### ISSUE THREAD

**Issue by Vonfry** [Infinisil/all-hies#24]
Is there a way to let all-hies install with this version automatically? I mean if it is updated on nixpkgs' channel, all-hies can select the new version without manually editting. 

For example, now version of ghc on nixos(19.03) stable is 8.6.4, and hie with this version should be installed. If it is updated to other version, such as 9.0.0, hie will select the new version without editting configuration on users' system when rebuilding/updating the system.

**Comment by Vonfry** [comment]
I find a solution.

```
{ lib, ghc, useSystem ? true, useLatest ? false, versions ? [] }:

let
  all-hies = import (fetchTarball "https://github.com/infinisil/all-hies/tarball/master") {};
  ghcVersionList = builtins.splitVersion ghc.version;
  ghcVersionToString = builtins.foldl' (x: y: x + y) "" ghcVersionList;
  ghcVersionKey = "ghc${ghcVersionToString}";
  versionList = versions
    ++ (if useSystem then [ ghcVersionKey ] else [])
    ++ (if useLatest then [ lib.last (lib.attrValues versions) ] else []);
  selector = p: builtins.foldl' (a: b: a // b) {} (map (v: { ${v} = p.${v}; }) versionList);
in all-hies.selection { selector = selector; }
```

**Comment by infinisil** [comment]
That's a good idea. I think https://github.com/Infinisil/all-hies/pull/13 would allow for that, so I'll look into getting that PR finished

**Comment by schmittlauch** [comment]
That'd be very convenient. When using lorri and project-specific environments, all of them are usually rebuild automatically on channel updates, avoiding multiple ghc versions.
And #6 even looks like it could solve that when using pinned nixpkgs revisions for a project.

**Comment by infinisil** [comment]
With #64 now merged, an overlay is the only way to use this project. This now allows getting the correct HIE version automatically for your Haskell project (see also the templates directory showing this: https://github.com/Infinisil/all-hies/tree/master/templates). Unfortunately haskell.nix only works with versions 8.6.5 and 8.8.3 for now, but that's the best we can do for now.
