### ISSUE TITLE
Error during `update` run

### ISSUE THREAD

**Issue by drchaos** [Infinisil/all-hies#25]
I have tryed to build `hie-bois` branch of `haskell-ide-engine` and saw that error after I run
`update --name bios --revision hie-bios`
```
ao-bmcapolim2lpneiirlx e gr-h -cgs-hu8cb.-p48a..t24h . c2.a  bc-aa-lbs:ay/ls/:tz/eo/mtz -sx0t8.d60-_.063.4
1-.l0i.n0u
x --compiler ghc-8.4.2 cabal://ztail-1.2.0.2
update: /tmp/all-hies-stack2nix18584-0: commitBuffer: invalid argument (invalid character)
```
the same error I saw when I've tried with `master` branch.
Am I doing something wrong?

**Comment by infinisil** [comment]
Looks like a stack2nix problem, can be checked by running stack2nix directly on the hie-bios branch

**Comment by drchaos** [comment]
I've found the problem nix is using higher glibc-locales.
So, installing glibcLocales package and running update with `LOCALE_ARCHIVE` fixes problem
```
LOCALE_ARCHIVE=~/.nix-profile/lib/locale/locale-archive update --name bios --revision hie-bios
```
But after that, I see another problem: `hie-bios` package is not included in generated ghcXXX.nix files. Maybe because it is not in `submodules` dir...

**Comment by drchaos** [comment]
Hm... seems like this thread is outdated. It is better to use https://github.com/mpickering/haskell-ide-engine

**Comment by drchaos** [comment]
BTW, It would be nice to add the ability to specify HIE repository.

**Comment by infinisil** [comment]
That's a fork of HIE for https://github.com/haskell/haskell-ide-engine/pull/1126 which is going to be merged into main HIE soonish. I might look into getting that to work.

**Comment by drchaos** [comment]
I've replaced the path to the repo in `Main.hs`, and your code just built it. Well done!

**Comment by infinisil** [comment]
I have since added https://github.com/Infinisil/all-hies/commit/a585074f75729de46669d859636ad5e9586a6a2a to address the LOCALE_ARCHIVE thing. Also the update script now supports a `--hie-repo` flag one can use to change the default repo. The hie-bios branch is now available too, see https://github.com/Infinisil/all-hies#hie-bios-versions :)
