### ISSUE TITLE
GHC 8.8.1 support

### ISSUE THREAD

**Issue by glittershark** [Infinisil/all-hies#26]
Looks like it's missing here

**Comment by infinisil** [comment]
8.8.1 support will come when HIE supports it, which is currently not the case unfortunately

**Comment by glittershark** [comment]
ah, fair.
Cabal 3 is also necessary (on the hie side) since that's what nixpkgs master is on now

**Comment by infinisil** [comment]
Yeah, unfortunately doesn't support Cabal 3 either, see https://github.com/haskell/haskell-ide-engine/issues/1376

Maybe both of those issues are fixed with hie-bios, I should try packaging hie-bios in all-hies

**Comment by infinisil** [comment]
Not sure if hie-bios solves this, but there's support for building it now: https://github.com/Infinisil/all-hies#hie-bios-versions

Anyways I'll close this issue as it's something that has to be implemented upstream.

**Comment by malob** [comment]
@Infinisil, I'm wondering if this issue should be reopened now that `hie` has merged support for GHC 8.8.1 into master. (See haskell/haskell-ide-engine#1482.)

**Comment by infinisil** [comment]
Yeah, I'll look into updating the unstable version for that, though it doesn't seem that easy because there's some problems with stack2nix/stackage.nix

**Comment by infinisil** [comment]
The error I got is now fixed: https://github.com/commercialhaskell/stackage-nightly/issues/6

**Comment by infinisil** [comment]
Updated [unstable](https://github.com/infinisil/all-hies#unstable-versions) to latest master in 0f09fb2faeb4e55acaae365e57503f498c08dc6d
