### ISSUE TITLE
Trying to build hie-bios version error

### ISSUE THREAD

**Issue by freeman42x** [Infinisil/all-hies#27]
Using the system package: `((import (fetchTarball "https://github.com/infinisil/all-hies/tarball/master") {}).bios.selection { selector = p: { inherit (p) ghc865; }; })` gives:

> haddockPhase
> installing
> Installing library in /nix/store/7r8qkbd81i73rai0ir7vqfy3sjm1n4v7-file-embed-0.0.11/lib/ghc-8.6.5/x86_64-linux-ghc-8.6.5/file-embed-0.0.11-4IE3sw0bCLQ7xXwEGMUYke
> [16 of 20] Compiling System.Info.Extra ( src/System/Info/Extra.hs, dist/build/System/Info/Extra.o )
> [17 of 20] Compiling System.Process.Extra ( src/System/Process/Extra.hs, dist/build/System/Process/Extra.o )
> remote: Total 478 (delta 8), reused 18 (delta 6), pack-reused 449
> Receiving objects: 100% (478/478), 102.77 KiB | 565.00 KiB/s, done.
> Resolving deltas: 100% (229/229), done.
> From https://github.com/mpickering/hie-bios
>  * [new branch]      clear-hook   -> origin/clear-hook
>  * [new branch]      master       -> origin/master
>  * [new branch]      multi-cradle -> origin/multi-cradle
>  * [new branch]      none-cradle  -> origin/none-cradle
>  * [new branch]      parse-test   -> origin/parse-test
>  * [new tag]         0.1.0        -> 0.1.0
>  * [new tag]         0.1.1        -> 0.1.1
>  * [new tag]         0.2.0        -> 0.2.0
>  * [new tag]         0.2.1        -> 0.2.1
> fatal: reference is not a tree: 28b592ae88b29bc11c11343c5a364949ae497a4f
> Unable to checkout 28b592ae88b29bc11c11343c5a364949ae497a4f from https://github.com/mpickering/hie-bios.git.
> builder for '/nix/store/3lpm3vl8p5589wmviqypqdiivrhbickq-haskell-ide-engine-eb3d32e.drv' failed with exit code 1
> building '/nix/store/0jammaj1ar4af4ksryhwfamcvi88qzss-firefox-release-bin-unwrapped-69.0.2.drv'...
> cannot build derivation '/nix/store/pd45asf86qswhm4c35g0vlb28qncznbz-haskell-ide-engine-ghc865-eb3d32e32b.drv': 1 dependencies couldn't be built
> building '/nix/store/cr4v9qgz2i8x1av5qm8x899fb90z3h6m-slack-4.0.2.drv'...
> building '/nix/store/7as5xypvyw5wbpdnvqxrpzx6zk2azc2g-steam-runtime-2016-08-13.drv'...
> building '/nix/store/9vhfr3va219rq973hy6jghwayk34cnwp-steam-runtime-2016-08-13.drv'...
> building '/nix/store/frm6rym27mma9q1svgf13pmhk8klkay6-steam-wrapper.sh.drv'...
> building '/nix/store/90g63yb1pqffkc9l73dfjn0rksmpdpk7-vscode-1.39.1.drv'...
> building '/nix/store/82mn56ifygyy314g02xwdbfrkkwcms4f-zoom_x86_64.tar.xz.drv'...
> cannot build derivation '/nix/store/4xx8sa9sac90nxwmwfn48nijv96dy8kl-haskell-ide-engine-combined.drv': 1 dependencies couldn't be built
> cannot build derivation '/nix/store/21k07vnba1ndcqnfai86i5ngppz1r3jf-system-path.drv': 1 dependencies couldn't be built
> cannot build derivation '/nix/store/rh8w0v3sjihr16m2ksq1kgi0zz3k5pa0-nixos-system-nixos-19.03.173553.6420e2649fa.drv': 1 dependencies couldn't be built
> error: build of '/nix/store/rh8w0v3sjihr16m2ksq1kgi0zz3k5pa0-nixos-system-nixos-19.03.173553.6420e2649fa.drv' failed

**Comment by infinisil** [comment]
Just saw somebody else have the same problem yesterday. Apparently the hie-bios ref was deleted/unreferenced. I did have a cached version of this derivation however, which I have since uploaded to the all-hies cachix. So enabling the cache as described in https://github.com/infinisil/all-hies#cached-builds should make this work.

Or getting the non-buildable path directly:
```
nix-store -r /nix/store/hji603fygfz3a5kkkkzwrf3cfgjpj9d6-haskell-ide-engine-eb3d32e \
  --option substituters https://all-hies.cachix.org \
  --option trusted-public-keys all-hies.cachix.org-1:JjrzAOEUsD9ZMt8fdFbzo3jNAyEWlPAwdVuHw4RD43k=
```

I could alternatively update the hie-bios version again, but there's no guarantee this won't happen again, so I think this is the best course of action for now.

**Comment by fendor** [comment]
I got bit by that, too, today.
This will probably not happen again since the branch of hie-bios (multi-cradle) we are using is going to be merged into master of hie-bios and then there will be another release at some point, making the submodule of hie-bios obsolete, removing this potential pain point in the future.
Tomorrow, we will fix this on the hie-bios branch in Haskell-IDE-Engine.

**Comment by infinisil** [comment]
@fendor That would be awesome :D. For now I just added above command to the Readme in 3030c7dc469b30542e954d177c49f6de0aefe2ed as a temporary workaround

**Comment by freeman42x** [comment]
@Infinisil I added the cachix but did not know the NixOS command to restart the nix daemon so I rebooted. After reboot on install I am still getting the same issue.

**Comment by infinisil** [comment]
@razvan-flavius-panda Try running
```
nix-store -r /nix/store/3lpm3vl8p5589wmviqypqdiivrhbickq-haskell-ide-engine-eb3d32e.drv -vv
```

What does it output?

**Comment by fendor** [comment]
Build is fixed with commit https://github.com/haskell/haskell-ide-engine/pull/1126/commits/2ff38936999831641209a086751f9b41732690ea

**Comment by freeman42x** [comment]
@Infinisil Running the command gave:

[neo@nixos:~]$ nix-store -r /nix/store/hji603fygfz3a5kkkkzwrf3cfgjpj9d6-haskell-ide-engine-eb3d32e \
>   --option substituters https://all-hies.cachix.org \
>   --option trusted-public-keys all-hies.cachix.org-1:JjrzAOEUsD9ZMt8fdFbzo3jNAyEWlPAwdVuHw4RD43k=
these paths will be fetched (3.07 MiB download, 14.85 MiB unpacked):
  /nix/store/hji603fygfz3a5kkkkzwrf3cfgjpj9d6-haskell-ide-engine-eb3d32e
copying path '/nix/store/hji603fygfz3a5kkkkzwrf3cfgjpj9d6-haskell-ide-engine-eb3d32e' from 'https://all-hies.cachix.org'...
warning: you did not specify '--add-root'; the result might be removed by the garbage collector
/nix/store/hji603fygfz3a5kkkkzwrf3cfgjpj9d6-haskell-ide-engine-eb3d32e

**Comment by freeman42x** [comment]
@Infinisil I built it after running your `nix-store -r ...` command and it installed fine I think.

**Comment by freeman42x** [comment]
But when running HIE I get the following errors:

> "can't load .so/.DLL for: libz.so (libz.so: cannot open shared object file: No such file or directory)"


> "panic! (the 'impossible' happened)\n (GHC version 8.6.5 for x86_64-unknown-linux):\n\tDynamic linker not initialised\n\nPlease report this as a GHC bug: http://www.haskell.org/ghc/reportabug\n"

**Comment by infinisil** [comment]
Nice that it builds at least, not sure what to do about that error though. With the change @fendor announced I think I'll update the expressions again.
