### ISSUE TITLE
Cached versions of hie-bios

### ISSUE THREAD

**Issue by korayal** [Infinisil/all-hies#33]
I have a project that requires Cabal 3 support so I wanted to try out the `hie-bios` version via the command:

```
nix-env -iA bios.selection --arg selector 'p: { inherit (p) ghc865; }' -f https://github.com/infinisil/all-hies/tarball/master
```
But it looks like it does not hit the all-hies cache at Cachix. (so the command above took ~45 minutes)

**Comment by infinisil** [comment]
I'm indeed not providing caches for the hio-bios version, maybe I should point that out in the Readme. Doing the caches for the 18 normal versions strains my machines already enough :) (though nix's dependency reuse helps a lot)
