### ISSUE TITLE
Question: navigate to definition, show type and hsimport

### ISSUE THREAD

**Issue by mananamenos** [Infinisil/all-hies#34]
hi, I was able to set up nixos, lsp-mode, haskell-lsp and bios-hie to work in emacs? However, xref stuff of lsp-mode does not seem to work.
I can use hstags and haskell-mode's generate tags or just start cabal-new-repl process on every project's file and then i can navigate to the definitions of my own code only. Yet i cannot jump to prelude functions' implementions. Is there something i should do to make lsp-mode work with 'go to definition and show-type'? What do you use?

Also I have hsimport binary and do not know how to use it from emacs with lsp-mode? Is it possible?

Thanks

**Comment by infinisil** [comment]
- HIE doesn't work with new-build commands just yet and consequently it doesn't work with Cabal 3.0.0.0 either (see https://github.com/haskell/haskell-ide-engine/issues/1376)
- HIE can only jump to function definitions in your own code, not the Prelude

**Comment by fendor** [comment]
Regarding hsimport, you need to generate a hoogle database, e.g. `hoogle generate`, or `stack exec hoogle generate` or something like this.
Then Hie should generate code-actions that you can apply.

And btw, hie supports from now on Cabal-3.0.0.0!

**Comment by infinisil** [comment]
With #64 merged, there is now a set of templates that demonstrate how to get a local hoogle database with all your dependencies: https://github.com/Infinisil/all-hies/tree/master/templates

Otherwise this issue is mostly not related to all-hies, so closing for now
