### ISSUE TITLE
update to version that supports cabal 3

### ISSUE THREAD

**Issue by srghma** [Infinisil/all-hies#38]
which includes this https://github.com/haskell/haskell-ide-engine/pull/1126 (merged 5 days ago)

support for cabal 3

**Comment by Infinisil** [comment]
Done in 85fd0be92443ca60bb649f8e7748f785fe870b7a

**Comment by srghma** [comment]
Thank you!

**Comment by andys8** [comment]
Now released as [1.0.0.0](https://github.com/haskell/haskell-ide-engine/releases/tag/1.0.0.0) :)

**Comment by Infinisil** [comment]
Yup saw that, I'll get to updating all-hies soon

**Comment by Infinisil** [comment]
See #39
