### ISSUE TITLE
Question about how to use cached binaries within a nix-shell project.

### ISSUE THREAD

**Issue by drewboardman** [Infinisil/all-hies#44]
I currently have a project that I work on with `nix-shell`, and it has its own dependencies. I'm using an impure shell, so I can see system binaries from within the shell.

```shell
drew@muaddib ~/code/widengle (master*) $ which cabal
/nix/store/50grv7dgbi2nxbhhig8bhv3ajqam9aah-cabal-install-2.4.1.0/bin/cabal
drew@muaddib ~/code/widengle (master*) $ which hie-wrapper
/home/drew/.local/bin/hie-wrapper
```

However, after going through the [cachix steps](https://all-hies.cachix.org/) I would have expected that last call to reference a nix dependency.

Am I missing a step here?

**Comment by infinisil** [comment]
You still need to actually install it after configuring the cache, see https://github.com/Infinisil/all-hies#declarative-installation-nixos-home-manager-or-similar and later sections

**Comment by drewboardman** [comment]
Yep, I used the later section and it worked!

Do you have any plans to make something similar to this for `ghcide` or the new `haskell/ide`?

**Comment by infinisil** [comment]
For ghcide there's https://github.com/hercules-ci/ghcide-nix/. For the new `ide` thing I'm not sure yet, maybe I'll do something like this for it too (but then with `haskell.nix` probably).

**Comment by drewboardman** [comment]
Have you seen anything like this happen before in your projects?

https://github.com/haskell/haskell-ide-engine/issues/1613

**Comment by drewboardman** [comment]
> For ghcide there's https://github.com/hercules-ci/ghcide-nix/. For the new `ide` thing I'm not sure yet, maybe I'll do something like this for it too (but then with `haskell.nix` probably).

How do I update my cachix and get the new `hie --debug` that you added?

**Comment by infinisil** [comment]
As mentioned on IRC, you should be able to do `nixos-rebuild switch` or whatever you're using, to update all-hies. And I added `hie-bios`, not `hie --debug`.

**Comment by drewboardman** [comment]
I don't know if there is an equivalent for this with `nix` package manager. Does running the install command replace my current binary with the latest?

```
nix-env -iA selection --arg selector 'p: { inherit (p) ghc864; }' -f https://github.com/infinisil/all-hies/tarball/master
```

**Comment by infinisil** [comment]
As mentioned on IRC, yes it does
