### ISSUE TITLE
How to update hie when changes are pushed onto master?

### ISSUE THREAD

**Issue by drewboardman** [Infinisil/all-hies#45]
There are some bug fixes coming that I'd like to have. Do the cached binaries track upstream? If so, how do I locally update my cached binaries to get those changes?

**Comment by fendor** [comment]
No, all-hies does not provide cached binaries for anything else than releases. However, for hie, there will be a release soon.

**Comment by drewboardman** [comment]
Does this release contain the `+RTS` issue we spoke about in the hie issues?

**Comment by fendor** [comment]
Hopefully, but I can not promise it
