### ISSUE TITLE
Does this tool allow to install hie with hoogle docs?

### ISSUE THREAD

**Issue by andriy-f** [Infinisil/all-hies#47]
Relevant section in hie readme:

```
Install hie for a specific GHC version (and hoogle docs):

stack ./install.hs hie-8.6.5
stack ./install.hs data
```

**Comment by infinisil** [comment]
Not as of now, because it would be very complex to package this with Nix, since the doc generation is very much impure. I've opened https://github.com/haskell/haskell-ide-engine/issues/1285 in the hopes of HIE changing the hoogle doc approach

**Comment by andriy-f** [comment]
Ok thanks

**Comment by infinisil** [comment]
With #64 merged, there is now a set of templates showing a working hoogle database setup :)
