### ISSUE TITLE
linking error with ghc-prim

### ISSUE THREAD

**Issue by schmittlauch** [Infinisil/all-hies#54]
When using hie together with vim and its ale plugin, I get the following error on startup:

``Error:hie: "can't load .so/.DLL for: /nix/store/4kfzb7z5jgysqmrjy18q2ir903nfi8dx-ghc-8.6.5/lib/ghc-8.6.5/ghc-prim-0.5.3/libHSghc-prim-0.5.3-ghc8.6.5.so (/nix/store/c745s6cnnxy6c98bvhi0qsijrh3ikag1-glibc-2.27/lib/libm.so.6: version `GLIBC_2.29' not found (required by /nix/store/4kfzb7z5jgysqmrjy18q2ir903nfi8dx-ghc-8.6.5/lib/ghc-8.6.5/ghc-prim-0.5.3/libHSghc-prim-0.5.3-ghc8.6.5.so))"
``

Shortly afterwards I get the following error:

```
Error:hie: "panic! (the 'impossible' happened)
  (GHC version 8.6.5 for x86_64-unknown-linux):
	Dynamic linker not initialised

Please report this as a GHC bug:  http://www.haskell.org/ghc/reportabug
"
```

But as the previous error showed some linker issue possibly caught by the nix packaging, I first wanted to check whether this bug is caused by the Nix packaging before bothering upstream hie or GHC.

~Interestingly, just running `hie-wrapper` or `hie-wrapper --lsp` does not trigger this error, only the invocation through the vim ale plugin.~

Any ideas on what's going on?

distro: NixOS 20.03 beta
GHC version: 8.6.5
HIE version: Version 1.1 x86_64 ghc-8.6.5

**Comment by schmittlauch** [comment]
Update: Turns out that running `hie-wrapper` in the project directory *does* cause the same error.
See the attached [full log](https://github.com/Infinisil/all-hies/files/4402512/hielog.txt)

**Comment by poscat0x04** [comment]
dup https://github.com/Infinisil/all-hies/issues/32

**Comment by schmittlauch** [comment]
Sorry, completely missed that.
