### ISSUE TITLE
Provide an overlay

### ISSUE THREAD

**Issue by infinisil** [Infinisil/all-hies#6]
Both makes sense and makes installation simpler.

**Comment by jhenahan** [comment]
The overlay I use is just

```nix
self:
  super:
{
  all-hies = import (fetchTarball "https://github.com/infinisil/all-hies/tarball/master") {};
}
```

Do you have something more featureful in mind?

**Comment by infinisil** [comment]
I'd have the overlay define `hie` or `haskell-ide-engine` as the attribute name, since that's what the package should really be called.

And of course the overlay in this repo would use the expressions defined within directly, instead of fetching the repo again. Use would look like

```nix
{
  nixpkgs.overlays = [
    (import (fetchTarball "https://github.com/infinisil/all-hies/tarball/master" + "/overlay.nix"))
  ];
  
  environment.systemPackages = with pkgs; [
    (hie.selection { selector = p: { inherit (p) ghc844 ghc864; }; })
  ];
}
```

Or actually even better, use [NUR](https://github.com/nix-community/NUR)

**Comment by infinisil** [comment]
And even better on NixOS, a module like this:

```nix
{
  imports = [
    (import (fetchTarball "https://github.com/infinisil/all-hies/tarball/master" + "/module.nix"))
  ];

  programs.hie = {
    enable = true;
    ghcVersions = [ "ghc864" "ghc865" ];
    fallbackToUnstable = true;
  };
}
```

Then this can guarantee that only one combined version of HIE gets installed but you can still add additional versions from different files.

**Comment by infinisil** [comment]
Ohh and actually, an overlay can do something really fancy: It can add the correct HIE version to all haskell package sets! So you'd have a correct HIE under `pkgs.haskell.packages.ghc864.haskell-ide-engine` and the same for all others.

**Comment by infinisil** [comment]
Now done with #64
