### ISSUE TITLE
Please, provide explicit description of the project status

### ISSUE THREAD

**Issue by Anton-Latukha** [Infinisil/all-hies#60]
Switch to haskell.nix https://github.com/Infinisil/all-hies/issues/19
The situation is unknown for the people who does not follow the debate.

Also HIE would migrate.

Maybe add the related guidance, branches, and future information to the main page.

I have a classic parable about Spacemacs, it is hilarious. My link that right away noded people into develop - was there for 3 years. It got removed from the front page. "Someone" there keeps making a tremendous effort to ignore that stable (good name for a side-branch) releases never happen so "someone" just hides the main development branch from everyone where all active community lives. Probably "someone" wants to just fend off all new users and contributors of the project.

**Comment by infinisil** [comment]
The project is now updated (maybe for a final time) with #64 :)
