### ISSUE TITLE
migrate to haskell-language-server

### ISSUE THREAD

**Issue by fatmalama** [Infinisil/all-hies#69]
there won't probably be anymore updates to haskell-ide-engine as pointed out in their README.hs, and indeed, commits stopped on June 15

https://github.com/haskell/haskell-language-server is the new one

**Comment by infinisil** [comment]
See https://github.com/haskell/haskell-language-server/issues/122 for installing HLS with Nix. I don't intend to update all-hies for HLS as I think there might be no need for it, especially with HLS being in nixpkgs now (which wasn't really possible with HIE).

That said, anybody is free to fork this project and adapting it for HLS if they need something like it :)
